mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-conf.xml
  type-aliases-package: com.eumji.date.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/date-demo?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: date-demo
  redis:
    host: localhost
    port: 6379
    database: 0


server:
  port: 8080
logging:
  config: classpath:log4j2.xml
  level: info





