mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-conf.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/date-demo?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: date-demo
server:
  port: 8080


